npmPublishAccess: public
initScope: ooee
initFields:
  license: MIT
  version: 0.0.1
  author: FIXME
  repository:
    type: git
    url: "git+https://github.com/CITguy/ooee.git"
  bugs:
    url: "https://github.com/CITguy/ooee/issues"
  homepage: "https://github.com/CITguy/ooee#readme"
  publishConfig:
    access: public
